from flask import Blueprint
from Handlers.statistics import statisticsHandler
from DDoSMitigator import DDoSMitigator  

statistics_bp = Blueprint('statistics_bp', __name__)
functions = statisticsHandler()
ddos_mitigator = DDoSMitigator()

statistics_bp.add_url_rule('/DummyWebsite/statistics/customersByCity', view_func=ddos_mitigator.apply_mitigations(functions.customerDistributionByCity), methods=['GET'])
statistics_bp.add_url_rule('/DummyWebsite/statistics/customersByCountry', view_func=ddos_mitigator.apply_mitigations(functions.customerDistributionByCountry), methods=['GET'])
statistics_bp.add_url_rule('/DummyWebsite/statistics/totalNumTransactions', view_func=ddos_mitigator.apply_mitigations(functions.totalNumberOfTransactions), methods=['GET'])
statistics_bp.add_url_rule('/DummyWebsite/statistics/top10ItemSellers', view_func=ddos_mitigator.apply_mitigations(functions.top10ItemSellers), methods=['GET'])
statistics_bp.add_url_rule('/DummyWebsite/statistics/getAllPeople', view_func=ddos_mitigator.apply_mitigations(functions.getAllPeople), methods=['GET'])
statistics_bp.add_url_rule('/DummyWebsite/statistics/storeMostTransactions', view_func=ddos_mitigator.apply_mitigations(functions.storeMostTransactions), methods=['GET'])
statistics_bp.add_url_rule('/DummyWebsite/statistics/mostUsedDevice', view_func=ddos_mitigator.apply_mitigations(functions.mostUsedDevice), methods=['GET'])
statistics_bp.add_url_rule('/DummyWebsite/statistics/highestSpendingCustomer', view_func=ddos_mitigator.apply_mitigations(functions.highestSpendingCustomer), methods=['GET'])
statistics_bp.add_url_rule('/DummyWebsite/statistics/customerCount', view_func=ddos_mitigator.apply_mitigations(functions.getCustomerCount), methods=['GET'])
statistics_bp.add_url_rule('/DummyWebsite/statistics/countryMostUsers', view_func=ddos_mitigator.apply_mitigations(functions.countryMostUsers), methods=['GET'])
statistics_bp.add_url_rule('/DummyWebsite/statistics/cityMostUsers', view_func=ddos_mitigator.apply_mitigations(functions.cityMostUsers), methods=['GET'])
statistics_bp.add_url_rule('/DummyWebsite/statistics/avgTransaction', view_func=ddos_mitigator.apply_mitigations(functions.averageTransaction), methods=['GET'])
statistics_bp.add_url_rule('/DummyWebsite/statistics/storeLeastTransactions', view_func=ddos_mitigator.apply_mitigations(functions.storeLeastTransactions), methods=['GET'])
statistics_bp.add_url_rule('/DummyWebsite/statistics/totalTransfers', view_func=ddos_mitigator.apply_mitigations(functions.totalTransfers), methods=['GET'])
statistics_bp.add_url_rule('/DummyWebsite/statistics/receivedMostTransfers', view_func=ddos_mitigator.apply_mitigations(functions.receivedMostTransfers), methods=['GET'])
statistics_bp.add_url_rule('/DummyWebsite/statistics/sentMostTransfers', view_func=ddos_mitigator.apply_mitigations(functions.sentMostTransfers), methods=['GET'])
statistics_bp.add_url_rule('/DummyWebsite/statistics/totalPromotions', view_func=ddos_mitigator.apply_mitigations(functions.totalPromotions), methods=['GET'])
statistics_bp.add_url_rule('/DummyWebsite/statistics/totalRespondedPromotions', view_func=ddos_mitigator.apply_mitigations(functions.totalRespondedPromotions), methods=['GET'])
statistics_bp.add_url_rule('/DummyWebsite/statistics/totalNotRespondedPromotions', view_func=ddos_mitigator.apply_mitigations(functions.totalNotRespondedPromotions), methods=['GET'])
statistics_bp.add_url_rule('/DummyWebsite/statistics/topCompaniesPromotionsCount', view_func=ddos_mitigator.apply_mitigations(functions.topCompaniesPromotionsCount), methods=['GET'])
statistics_bp.add_url_rule('/DummyWebsite/statistics/largestTransfers', view_func=ddos_mitigator.apply_mitigations(functions.top10HighestTransfers), methods=['GET'])
statistics_bp.add_url_rule('/DummyWebsite/statistics/transfersByDate', view_func=ddos_mitigator.apply_mitigations(functions.transfersByDate), methods=['GET'])
statistics_bp.add_url_rule('/DummyWebsite/statistics/storeTransactionCounts', view_func=ddos_mitigator.apply_mitigations(functions.storeTransactionCounts), methods=['GET'])
